### ISSUE TITLE
Add ability for user to provide own logger

### ISSUE THREAD

**Issue by ryansonshine** [dbartholomae/middy-middleware-json-error-handler#150]
** Would you be willing to help with a PR? **
- [x] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
The ability for a user to provide their own logger. Similar to the middy http-error-handler:

i.e.
> ## options
> logger (defaults to console.error) - a logging function that is invoked with the current error as an argument. You can pass false if you don't want the logging to happen.

**Comment by dbartholomae** [comment]
Sure! [`JSONErrrorMiddleware` and its static `create` method](https://github.com/dbartholomae/middy-middleware-json-error-handler/blob/main/src/JSONErrorHandlerMiddleware.ts#LL23C15-L23C40) could take an options object with a `logger` property.

I would have a slight preference for first encapsulating the logger in a `DebugLogger` class that implements
```ts
interface ILogger {
  debug (msg: string): void;
}
```
which conforms to the `console` interface, and then by default setting `this.logger` to `new DebugLogger('middy-middleware-json-error-handler')`, but allowing different loggers from the parameter object. This way, user can just plug in bunyan, console, or whatever they want, without needing to follow the specific interface used by `debug`. Also, this automatically sets the right logging level of `debug` for all messages - currently, only debug messages are logged.

For contributing, feel free to open a PR even in between and mention any problems you run into, I'm happy to help and am usually able to answer quickly. Please note that this repo requires 100% test coverage. I don't think that an integration test is necessary for this feature, though.
Also, please note that this repo is using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). All commits need to follow this format, and every commit that is a `fix` or a `feat` will show up in the Changelog and dictate which version number will be used for a release. In practice: Make sure that you have 1 `feat` commit that actually describes the feature as you would like to see it in the changelog, and either squash all changes into this one commit, or use `test` and `refactor` commits for the rest.

Last but not least: Thanks for your interest in contributing!
