### ISSUE TITLE
Support of expose parameter of HttpError

### ISSUE THREAD

**Issue by LudoPL** [dbartholomae/middy-middleware-json-error-handler#208]
The current implementation don't return the error message when the error code is > 500, and there is no way to override this behaviour.
The HttpError library allow to use a property "expose" to indicate if we want the error message to be sent to the client or not.
It would be great if this library support this parameter (see [https://www.npmjs.com/package/http-errors](https://www.npmjs.com/package/http-errors)).

** Would you be willing to help with a PR? **
- [ ] Yes, absolutely
- [ ] Yes, with some guidance
- [X] Unfortunately no time :'-(

## Describe the solution you'd like
When a http error is created with the value true for `expose` parameter, for example whith `createHttpError(500, err.getErrorCode(), { expose : true})`, the response should contains the error message even if the status code is greater than or equals to 500.
At the contrary if the `expose` parameter is false, the error message should not be returned to the client even if the error code is lower than 500.
If the `expose` parameter is not set, current behaviour should still apply.

**Comment by dbartholomae** [comment]
Thanks! I would be happy to have this feature in the library. I won't be able to work on this myself, but can support either you or someone else who is interested to get it landed.

**Comment by dbartholomae** [comment]
@asargento Nice! Happy to support. I tried to write a short but helpful [CONTRIBUTING.md](https://github.com/dbartholomae/middy-middleware-json-error-handler/blob/main/CONTRIBUTING.md) as a starting point, but you can also just set up a PR with some first ideas and I'll guide you from there.
