### ISSUE TITLE
Dependency Overloading

### ISSUE THREAD

**Issue by suphero** [dbartholomae/middy-middleware-json-error-handler#23]
After I install the middleware to my application, my package-lock.json file and bundled serverless app size increased so much. It seems that using [snyk package](https://github.com/dbartholomae/middy-middleware-json-error-handler/blob/master/package.json#L31) in dependencies is the reason. I don't know much about [this package](https://www.npmjs.com/package/snyk) but I didn't see any reference in the source code. I assume this package can be moved to the devDependencies block so bundled app size can be reduced.

**Comment by dbartholomae** [comment]
See the discussion in #22: This is how Snyk operates.
Here's the reasoning behind this from Snyk: https://support.snyk.io/hc/en-us/articles/360000911277-Why-has-Snyk-been-added-as-a-dependency-in-my-project-

I will take another look at this over the next 2 weeks (unfortunately won't be able to do before) and see if I can and should disable this behavior as described in the article, or switch over to a different security solution.

**Comment by dbartholomae** [comment]
Here's the relevant issue at Snyk:
https://github.com/snyk/snyk/issues/1231

**Comment by suphero** [comment]
Thanks for the answer, I'm looking forward to your second review.

**Comment by dbartholomae** [comment]
Has been fixed in https://github.com/dbartholomae/middy-middleware-json-error-handler/commit/61674b87fc4a7b897efa0d624fd4a5d0117215b9
