### ISSUE TITLE
Optionally specify which are the error properties to omit from the response

### ISSUE THREAD

**Issue by asargento** [dbartholomae/middy-middleware-json-error-handler#255]
**Is your feature request related to a problem? Please describe.**
The current implementation is removing from the response one of the error properties, the `stack`.
It would be nice to configure which are the other properties that we can omit: statusCode, name or even message.

** Would you be willing to help with a PR? **
- [X] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
Add an option parameter on the class constructor with the `errorPropertiesToOmit`. This option would be an array with the fields to omit. By default, `stack` would be omited.

**Comment by dbartholomae** [comment]
Sounds interesting! Both the constructor of `JSONErrorHandlerMiddleware` and `JSONErrorHandlerMiddleware.create` could take an options object as parameter which is persisted in a class property. You could use a few unit tests similar to the one that checks whether it [strips the stack](https://github.com/dbartholomae/middy-middleware-json-error-handler/blob/main/src/JSONErrorHandlerMiddleware.spec.ts#L39).
I've also tried to write a short but useful [CONTRIBUTING.md](https://github.com/dbartholomae/middy-middleware-json-error-handler/blob/main/CONTRIBUTING.md).

**Comment by dbartholomae** [comment]
Thanks for the contribution! :)
