### ISSUE TITLE
How to correctly import this package using CommonJs Syntax?

### ISSUE THREAD

**Issue by major-mayer** [dbartholomae/middy-middleware-json-error-handler#27]
Hi,
just a quick question. I don't want to use ES6 module imports for my project because it already contains a lot of require statements.
So how should I correctly import this package?

Using just:
```
const errorHandler = require('middy-middleware-json-error-handler');
const middlewares = [errorHandler(), ...];
```
Gives me the error : `errorType":"TypeError","errorMessage":"JSONErrorHandlerMiddleware is not a function`

Right now i am using:
```
const errorHandler = require('middy-middleware-json-error-handler').JSONErrorHandlerMiddleware.create
const middlewares = [ errorHandler(), ... ]
```

But this seems pretty verbose. Is there a better option?

**Comment by dbartholomae** [comment]
```js
const errorHandler = require('middy-middleware-json-error-handler').default;
const middlewares = [errorHandler(), ...];
```

or

```js
const { default as errorHandler } = require('middy-middleware-json-error-handler');
const middlewares = [errorHandler(), ...];
```
should work :)

**Comment by major-mayer** [comment]
Yes seems to be working, thanks :)
