### ISSUE TITLE
Update serialize-error to version 11

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/middy-middleware-json-error-handler#282]
**Is your feature request related to a problem? Please describe.**
The newest version of serialize-error handles `cause` in errors. This update would allow the middleware to do the same.

## Describe the solution you'd like
Unsure so far how to update it, see Additional context below

## Describe alternatives you've considered
-

## Additional context
Unfortunately, the newer versions of serialize-error are ESM only. It would be great if this package could also be consumable as CommonJS, though.

**Comment by asargento** [comment]
I guess that we have the following options:
- don't do the bump and don't get the updates;
- do the bump and transform this package into an ESM only also;
- use other error serializer;
- implement the error serialization in this package.

What is necessary is to select one option 😄

**Comment by dbartholomae** [comment]
@asargento I've thought a bit about it and in case that you would be able to use it as an ESM package, the interest of quick iteration I would be willing to release a breaking version and think about supporting CommonJS once someone opens an issue (or comments here) that they actually can't use this with ESM :)
What do you think?

**Comment by asargento** [comment]
@dbartholomae Maybe we can have another approach and allow the Error serializer to be customizable as an option.
By default, be the `serializeError` from `serialize-error`. 
Now that we have `Options` in the constructor, why not 

```typescript
export interface Options {
  errorPropertiesToOmit?: string[],
  errorSerializer?: (error: IErrorWithStatusCode) => JsonObject. // JsonObject from type-fest
}
```

**Comment by dbartholomae** [comment]
I think that this won't work, as the default would need to be imported from the library, so we would need to then either anyways require ESM for importing the newest version, or people who want to use the new version will have both the new and old version in their dependency tree.
Based on your feedback, I would leave it for now and wait for someone asking for this :)
