### ISSUE TITLE
Add JSON response header

### ISSUE THREAD

**Issue by mpalenov** [dbartholomae/middy-middleware-json-error-handler#67]
**Is your feature request related to a problem? Please describe.**
The middleware serializes errors to JSON but does not set Content-Type header to application/json. It leads to the JSON content returned with text/plain content type.

** Would you be willing to help with a PR? **
- [ X] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
Set Content-Type header.

## Describe alternatives you've considered
It either should leave the content unserialized or set the header. Transformed error can be serialized to XML or some other types with serializer middleware.

**Comment by dbartholomae** [comment]
Sounds good! Looking forward to your PR :)
